version: "3.9"

services:
  web:
    build: .
    container_name: nutri_dash
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "${DB_PORT}:${DB_PORT}"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - nutri_dash_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_broker
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: celery_worker
    command: celery -A app.worker worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}

volumes:
  nutri_dash_postgres_data:
