services:
  nutri_web:
    build: .
    container_name: nutri_web
    command: ./start.sh
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - nutriDash_db
      - rabbitmq
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - PYTHONPATH=/app
    networks:
      - nutridashboard-rede
      - nutri_dash
      - rabbit_net

  nutriDash_db:
    image: postgres:17.5
    container_name: nutriDash_db
    env_file:
      - .env
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: America/Sao_Paulo
    volumes:
      - nutri_dash_postgres_data:/var/lib/postgresql/data
    networks:
      - nutri_dash
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - rabbit_net

volumes:
  nutri_dash_postgres_data:

networks:
  nutri_dash:
    driver: bridge
  nutridashboard-rede:
    external: true
    name: nutridashboard-rede
  rabbit_net:
    external: true
  
  