
services:
  web:
    build: .
    container_name: nutri_dash
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - nutriDash_db
      - redis
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - PYTHONPATH=/app

  nutriDash_db:
    image: postgres:17.5
    container_name: nutriDash_db
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - nutri_dash_postgres_data:/var/lib/postgresql/data
    networks:
      - nutridashboard-rede

  redis:
    image: redis:7
    container_name: redis_broker
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: celery_worker
    command: celery -A app.worker worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - nutriDash_db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}

volumes:
  nutri_dash_postgres_data:

networks:
  nutridashboard-rede:
    driver: bridge
